### ISSUE TITLE
TypeError: l2_normalize() got an unexpected keyword argument 'axis'

### ISSUE THREAD

**Issue by RaiAbhishek** [normandipalo/faceID_beta#1]
I'm getting the above error raised during batch normalization of x1. The solutions I found are not very encouraging. Can you please suggest something ?
Thanks.
![image](https://user-images.githubusercontent.com/29359850/37472376-d81f22fc-2863-11e8-8104-ede7ccb9875d.png)

**Comment by RaiAbhishek** [comment]
The issue was resolved by changing the "tensorflow_backend.py" file.
return value of function l2_normalize was changed to:
return tf.nn.l2_normalize(x, dim=axis)

**Comment by benlee12** [comment]
tensorflow 1.8 can avoid this problem
