### ISSUE TITLE
Can't run python script.

### ISSUE THREAD

**Issue by theDiverDK** [normandipalo/faceID_beta#4]
Hi there, thanks for the .py version.

Hope you can help.

When running i get this error:

Traceback (most recent call last):
  File ".\faceid.py", line 486, in <module>
    model_final.evaluate([cop[0].reshape((1,200,200,1)), cop[1].reshape((1,200,200,1))], np.array([0.]))
  File "C:\Users\srei\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\engine\training.py", line 1768, in evaluate
    batch_size=batch_size)
  File "C:\Users\srei\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\engine\training.py", line 1476, in _standardize_user_data
    exception_prefix='input')
  File "C:\Users\srei\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\engine\training.py", line 123, in _standardize_input_data
    str(data_shape))
ValueError: Error when checking input: expected input_3 to have shape (200, 200, 4) but got array with shape (200, 200, 1)

**Comment by RaiAbhishek** [comment]
I came out of error by changing:
`cop = create_couple(faceid_val)`
`model_final.evaluate([cop[0].reshape((1,200,200,1)), cop[1].reshape((1,200,200,1))], np.array([0.]))`
to:
`cop = create_couple_rgbd(faceid_val)`
`model_final.evaluate([cop[0].reshape((1,200,200,4)), cop[1].reshape((1,200,200,4))], np.array([0.]))`
as the model won't accept input shapes (200,200,1), only (200,200,4).
maybe leave the issue open for suggestions.

**Comment by normandipalo** [comment]
Yes, sorry about that, I forgot to change that line and it didn't occur to me since I usually use the Notebook and skipped that block. Fixed that, thanks again.

**Comment by theDiverDK** [comment]
Thanks for the tip, did a git pull and tried again, now i get:

Traceback (most recent call last):
  File ".\faceid_beta.py", line 486, in <module>
    model_final.evaluate([cop[0].reshape((1,200,200,4)), cop[1].reshape((1,200,200,4))], np.array([0.]))
ValueError: cannot reshape array of size 40000 into shape (1,200,200,4)

**Comment by bikram42** [comment]
"ValueError: cannot reshape array of size 40000 into shape (1,200,200,4)"
error is shown after changing to 
cop = create_couple_rgbd("faceid_val/")
model_final.evaluate([cop[0].reshape((1,200,200,4)), cop[1].reshape((1,200,200,4))], np.array([0.]))

**Comment by QianGuangLin** [comment]
"ValueError: cannot reshape array of size 40000 into shape (1,200,200,4)"
error is shown after changing to
cop = create_couple_rgbd("faceid_val/")
model_final.evaluate([cop[0].reshape((1,200,200,4)), cop[1].reshape((1,200,200,4))], np.array([0.]))

I also encountered the same error. Do you have a solution?

**Comment by bikram42** [comment]
i did 

cop = create_couple_rgbd("faceid_val/")
result = model.predict([cop[0].reshape((1, 200, 200, 4)), cop[1].reshape((1, 200, 200, 4))])

**Comment by QianGuangLin** [comment]
Thank you bikram42! But
"NameError: name 'model' is not defined"
Error is shown after changing to
Cop = create_couple_rgbd("faceid_val/")
Result = model.predict([cop[0].reshape((1, 200, 200, 4)), cop[1].reshape((1, 200, 200, 4))])
Can you share your code? My email address is:  linqg1@163.com

**Comment by bikram42** [comment]
load the model and assign it to the variable "model".
eg - 
model = load_model(MODEL_SAVING_DIR, custom_objects={"contrastive_loss": contrastive_loss})

MODEL_SAVING_DIR is the path where you saved the model
and "contrastive_loss" is the loss function defined below

def contrastive_loss(y_true, y_pred):
    margin = 1.
    return K.mean((1. - y_true) * K.square(y_pred) + y_true * K.square(K.maximum(margin - y_pred, 0.)))
