### ISSUE TITLE
What's the worry with the .dat data?

### ISSUE THREAD

**Issue by mystao** [normandipalo/faceID_beta#5]
hi,
I  have got an error when i run this code? see the screenshot
![image](https://user-images.githubusercontent.com/29221718/37818492-4389e660-2eb5-11e8-843e-8700863b13b8.png)
I did some test,And there is some worry at line 481 in .dat file. this code can not break when variable i is 480, and return above error.  Is any difference or special about .dat file ending? I will appreciate for any help，thanks

**Comment by RaiAbhishek** [comment]
change:
`if val == "\n": continue`
to:
`if val == "\r\n": continue`
should be _line 86_ for you.

**Comment by mystao** [comment]
thank you for your reply!
I tried this way before , but I don't think so. I can figure this problem out by limiting variable i range from  0 to 480. but still don't get the reason why your code can not  correct return . thanks again.

**Comment by benlee12** [comment]
you need python 3+
